export enum USER_ACTION {
  LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE = 'USER_LOGIN_FAILURE',

  LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
  LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE',
}
